🚑️ Update DMC to MC_X motors
SJSURoboticsTeam/urc-control-system-2023 pull request #89
Opened 2023-04-22 21:50 UTC by FluffyFTW

- Update the DMC motors to MC_X motors
- Changed i2c line to 1 for the pca9685
- Updated ESP to connect to AWS server

2023-04-22 21:59 UTC, Coreyboy1820 approved these changes

2023-05-01 19:33 UTC, Coreyboy1820 requested changes
Just uncomment the items I told you to and merge it in.

2023-05-01 19:33 UTC, Coreyboy1820 commented on code/applications/control_loops/drive_serial.cpp
> +  // auto& magnet2 = *p_map.in_pin2;
Uncomment this and all other motors.

2023-05-01 20:01 UTC, Coreyboy1820 approved these changes

2023-05-12 19:51 UTC, Coreyboy1820 requested changes
Change the arm code to have the correct esp connection loop.

2023-05-12 20:44 UTC, kammce commented
Were you able to upgrade the MC_X firmware?

2023-08-27 01:04 UTC, closed without merging